appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.8.0
replicas: 2
containerPort: 8080
containerEnvVars:
  - name: port
    value: "8080"
  - name: DISABLE_TRACING
    value: "true"
  - name: DISABLE_PROFILER
    value: "true"


servicePort: 5000