appName: recommendationservice
appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v0.8.0
replicas: 2
containerPort: 8080
containerEnvVars:
  - name: PORT
    value: "8080"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: DISABLE_PROFILER
    value: "1"
  - name: DISABLE_TRACING
    value: "true"
  - name: DISABLE_DEBUGGER
    value: "true"

servicePort: 8080
