appName: servicename
appImage: gcr.io/google-samples/microservices-demo/servicename
appVersion: v0.8.0
replicas: 1
containerPort: 8080
containerEnvVars:
  - name: ENV_VAR_ONE
    value: "valuone"
  - name: ENV_VAR_TWO
    value: "valuetwo"

servicePort: 8080
serviceType: ClusterIP